url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "" # the name of your site, e.g. ACME Corp.

livereload: true

defaults:
  # Para todas as páginas e postagens
  - scope:
      path: "" # Aplica a todas as páginas e postagens
    values:
      layout: "default"
